### ISSUE TITLE
About training dataset

### ISSUE THREAD

**Issue by RammusLeo** [zju3dv/SA-HMR#2]
Hi! 
Thanks for your great work! Before reproducing the training procedure, I have few questions about downloading the dataset: 
```
1. You need to submit a request to the authors from MPI and use their links for downloading the full datasets. 
2. RICH: We use the JPG format image. We downsampled the image to **one-forth** of its original dimensions.
```
1. What is "MPI" refers to? 
2. For RICH, I notice that there are original training dataset for about 6TB and image dataset in JPG format in 500GB, does that mean I just need to download the JPG dataset only?
3. If it is convenient, would you like to share the script for downsampling the image data to one forth scale? It will helps me a lot to prepare the data.

Thanks again for your consideration and I'm looking forward to your reply!

**Comment by zehongs** [comment]
Hi, thanks for your interests in our work. (1) The MPI refers to Max Planck Institute for Intelligent Systems. (2) Yes. (3)I'm sorry that I can't provide the dataset due to the lincense.

**Comment by RammusLeo** [comment]
OK I got it! Thanks for your quick relpy!
