### ISSUE TITLE
Request for Missing Files

### ISSUE THREAD

**Issue by ChennyDeng** [zju3dv/SA-HMR#3]
Hi,

Thanks for the remarkable work you've produced. I've been working on reproducing the code for the project. However, I've encountered an issue in locating a couple of files that are mentioned in the readme. Specifically, I'm unable to find the files "metro_3dpw_state_dict.bin" and "sahmr_prox_e30.pth" (which is not present in the release folder).

I am reaching out to kindly inquire if it would be possible to receive the appropriate download links for these missing files. Your assistance in this matter would be immensely valuable to my efforts. Thank you very much for your time and consideration.

Best wishes,
Chenny

**Comment by zehongs** [comment]
Hi,
The sahmr_prox_e30.pth can be found in the folder of google-drive/release. https://drive.google.com/file/d/1BbcYHt92nyYOgiliaAjm--QLtp3HlGMF/view?usp=drive_link

And I think the download instruction for metro_3dpw_state_dict.bin is already in the README.md.
