### ISSUE TITLE
RICH - val datasets download

### ISSUE THREAD

**Issue by ChennyDeng** [zju3dv/SA-HMR#4]
Hi,

Thanks for the amazing work. 

I notice in the readme, it says, 'images_ds4: Please download the train and val datasets and downsample the images to one-forth of its original dimensions.' I tried to download the train and val datasets from the RICH website (https://rich.is.tue.mpg.de/download.php). 

However, in the RICH official website, the download link for the validation (JPG format images) is empty. More specifically, i try to download the JPG format validation dataset from the following link, 'We also provide JPG format images, around 250GB, you can download from [here](https://download.is.tue.mpg.de/download.php?domain=rich&resume=1&sfile=JPG_images/val.tar.gz).' But the downloaded file is empty. I wonder in this case, where can we find the relevant validation dataset that you use for validation in your code?

Thanks for your clarification.

Best wishes,
Chenny

**Comment by leoisufa** [comment]
same question
